# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-19 02:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='course_name', max_length=150, verbose_name='\u8bfe\u65f6\u540d\u79f0')),
                ('uptime', models.DateField(db_column='uptime', verbose_name='\u89c6\u9891\u4e0a\u4f20\u65f6\u95f4')),
                ('video', models.FileField(db_column='video_local', upload_to='./video', verbose_name='\u89c6\u9891\u4e0a\u4f20\u4f4d\u7f6e')),
                ('courseware', models.FileField(db_column='courseware', upload_to='./courseware', verbose_name='\u8bfe\u4ef6\u4e0a\u4f20\u4f4d\u7f6e')),
                ('lengtime', models.DecimalField(db_column='lengtime', decimal_places=2, max_digits=4, verbose_name='\u89c6\u9891\u65f6\u957f')),
                ('description', models.TextField(db_column='description', verbose_name='\u8bfe\u65f6\u7b80\u4ecb')),
            ],
        ),
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=20, verbose_name='\u804c\u4e1a\u8def\u5f84\u540d\u79f0')),
                ('desc', models.TextField(db_column='description', verbose_name='\u804c\u4e1a\u8def\u5f84\u7b80\u4ecb')),
                ('sections', models.CharField(db_column='sections', max_length=20, verbose_name='\u804c\u4e1a\u8def\u5f84\u5305\u542b\u7684\u8bfe\u7a0b')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.TextField(db_column='tag', verbose_name='\u8bfe\u7a0btag,\u4f9b\u68c0\u7d22')),
                ('sumtime', models.CharField(db_column='sumtime', max_length=10, verbose_name='\u8bfe\u7a0b\u603b\u65f6\u95f4')),
                ('description', models.TextField(db_column='description', verbose_name='\u8bfe\u7a0b\u63cf\u8ff0')),
            ],
        ),
        migrations.CreateModel(
            name='SectionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(db_column='color', max_length=10, verbose_name='\u989c\u8272')),
                ('sectiontype', models.CharField(db_column='sectiontype', max_length=50, verbose_name='\u8bfe\u7a0b\u7c7b\u578b')),
            ],
        ),
        migrations.AddField(
            model_name='section',
            name='sectiontype',
            field=models.ForeignKey(db_column='stypeid', on_delete=django.db.models.deletion.CASCADE, to='vcourse.SectionType', verbose_name='\u8bfe\u7a0b\u7c7b\u578b'),
        ),
        migrations.AddField(
            model_name='course',
            name='section',
            field=models.ForeignKey(db_column='section_id', on_delete=django.db.models.deletion.CASCADE, to='vcourse.Section'),
        ),
    ]
