# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-19 08:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vcourse', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='sectiontype',
            new_name='stypeid',
        ),
    ]
