# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-19 09:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vcourse', '0002_auto_20161219_0846'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='name',
            new_name='coursename',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='section',
            new_name='section_id',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='video',
            new_name='video_local',
        ),
    ]
