# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-19 10:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vcourse', '0003_auto_20161219_0959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='section_id',
        ),
        migrations.RemoveField(
            model_name='course',
            name='video_local',
        ),
        migrations.AddField(
            model_name='course',
            name='sectionid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vcourse.Section'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='videolocal',
            field=models.FileField(db_column='videolocal', default=1, upload_to='./video', verbose_name='\u89c6\u9891\u4e0a\u4f20\u4f4d\u7f6e'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='coursename',
            field=models.CharField(db_column='coursename', max_length=150, verbose_name='\u8bfe\u65f6\u540d\u79f0'),
        ),
    ]
