# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-19 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcourse', '0004_auto_20161219_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='path',
            name='sections',
        ),
        migrations.AddField(
            model_name='path',
            name='sections',
            field=models.ManyToManyField(to='vcourse.Section', verbose_name='\u804c\u4e1a\u8def\u5f84\u5305\u542b\u7684\u8bfe\u7a0b'),
        ),
    ]
