# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-20 10:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vcourse', '0005_auto_20161219_1126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='path',
            old_name='desc',
            new_name='description',
        ),
    ]
