# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-21 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcourse', '0007_course_pubstype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='pubstype',
        ),
        migrations.AddField(
            model_name='section',
            name='pubstype',
            field=models.IntegerField(choices=[(0, '\u5df2\u53d1\u5e03'), (1, '\u672a\u53d1\u5e03'), (2, '\u5373\u5c06\u53d1\u5e03')], default=1, verbose_name='\u53d1\u5e03\u72b6\u6001'),
        ),
    ]
