# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-22 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcourse', '0008_auto_20161221_0231'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='name',
            field=models.CharField(default=' ', max_length=50, verbose_name='\u8bfe\u7a0b\u6807\u9898'),
        ),
    ]
