# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-26 11:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vcourse', '0009_section_name'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='course',
            table='course',
        ),
        migrations.AlterModelTable(
            name='path',
            table='path',
        ),
    ]
