# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-26 11:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vcourse', '0010_auto_20161226_1142'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='course',
            table=None,
        ),
        migrations.AlterModelTable(
            name='path',
            table=None,
        ),
    ]
