# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-27 04:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vcourse', '0011_auto_20161226_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='path',
            name='createtime',
            field=models.IntegerField(default=0, verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
        migrations.AddField(
            model_name='path',
            name='sumtime',
            field=models.CharField(default='', max_length=20, verbose_name='\u5b8c\u6210\u8def\u7ebf\u6240\u9700\u8981\u7684\u65f6\u95f4'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='difficulty',
            field=models.SmallIntegerField(default=1, verbose_name='\u8bfe\u7a0b\u96be\u5ea6'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='uptime',
            field=models.IntegerField(db_column='uptime', verbose_name='\u89c6\u9891\u4e0a\u4f20\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(max_length=50, verbose_name='\u8bfe\u7a0b\u6807\u9898'),
        ),
        migrations.AlterField(
            model_name='section',
            name='stypeid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vcourse.SectionType', verbose_name='\u8bfe\u7a0b\u7c7b\u578b'),
        ),
    ]
