# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-27 04:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcourse', '0012_auto_20161227_0421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='difficulty',
            field=models.SmallIntegerField(default=1, verbose_name='\u8bfe\u7a0b\u96be\u5ea6'),
        ),
    ]
