# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-13 03:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='\u7528\u6237\u540d')),
                ('userid', models.CharField(max_length=128, unique=True, verbose_name='\u7528\u6237\u552f\u4e00ID')),
                ('sex', models.IntegerField(choices=[(0, '\u7537'), (1, '\u5973'), (2, '\u4fdd\u5bc6')], default=2, verbose_name='\u6027\u522b')),
                ('nickname', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u7528\u6237\u6635\u79f0')),
                ('birthday', models.DateField(blank=True, default='', null=True, verbose_name='\u751f\u65e5')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='\u90ae\u7bb1')),
                ('password', models.CharField(max_length=50, verbose_name='\u5bc6\u7801')),
            ],
        ),
    ]
