# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-22 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuser', '0002_auto_20161221_0229'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='regtime',
            field=models.IntegerField(default=1482390444, verbose_name='\u6ce8\u518c\u65f6\u95f4'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '\u5df2\u6fc0\u6d3b'), (1, '\u672a\u6fc0\u6d3b')], default=1, verbose_name='\u6fc0\u6d3b\u72b6\u6001'),
        ),
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(default='sfdsfsdfdsfs', max_length=50, verbose_name='\u8d26\u53f7\u6fc0\u6d3b\u7801'),
            preserve_default=False,
        ),
    ]
