# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-22 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuser', '0004_auto_20161222_0728'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uuid',
            field=models.CharField(default='23432dsfdsfdsf', max_length=50, verbose_name='UUID'),
            preserve_default=False,
        ),
    ]
