# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-26 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuser', '0005_user_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(0, 'SP'), (1, 'NO')], default=1, verbose_name='\u7528\u6237\u89d2\u8272'),
        ),
    ]
