# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-26 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuser', '0006_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sumscore',
            field=models.IntegerField(default=0, verbose_name='\u5b66\u4e60\u603b\u5f97\u5206'),
        ),
        migrations.AddField(
            model_name='user',
            name='sumtime',
            field=models.IntegerField(default=0, verbose_name='\u5b66\u4e60\u603b\u65f6\u95f4'),
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
