# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-26 11:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vuser', '0007_auto_20161226_1110'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
