# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-26 11:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vcourse', '0011_auto_20161226_1144'),
        ('vuser', '0008_auto_20161226_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(0, '\u672a\u89c2\u770b'), (1, '\u672a\u770b\u5b8c'), (2, '\u5df2\u770b\u5b8c')], verbose_name='\u662f\u5426\u770b\u5b8c\u89c6\u9891')),
                ('courseid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vcourse.Course', verbose_name='\u8bfe\u65f6ID')),
                ('sectionid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vcourse.Section', verbose_name='\u8bfe\u7a0bID')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vuser.User', verbose_name='\u7528\u6237ID')),
            ],
        ),
    ]
