# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-26 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuser', '0009_usercourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(0, 'Super'), (1, 'Normal')], default=1, verbose_name='\u7528\u6237\u89d2\u8272'),
        ),
    ]
