# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-27 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuser', '0011_auto_20161227_0343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.CharField(blank=True, default=' ', max_length=30, null=True, verbose_name='\u73b0\u5728\u6240\u5728\u7684\u516c\u53f8'),
        ),
        migrations.AlterField(
            model_name='user',
            name='companylocl',
            field=models.CharField(blank=True, default=' ', max_length=50, null=True, verbose_name='\u6240\u5728\u516c\u53f8\u5730\u5740'),
        ),
        migrations.AlterField(
            model_name='user',
            name='exceptjob',
            field=models.CharField(default=' ', max_length=100, null=True, verbose_name='\u671f\u671b\u5de5\u4f5c'),
        ),
        migrations.AlterField(
            model_name='user',
            name='exceptlevel',
            field=models.IntegerField(choices=[(1, '\u521d\u7ea7'), (2, '\u4e2d\u7ea7'), (3, '\u9ad8\u7ea7')], default=3, verbose_name='\u671f\u671b\u5de5\u4f5c\u7ea7\u522b'),
        ),
        migrations.AlterField(
            model_name='user',
            name='homepage',
            field=models.CharField(blank=True, default=' ', max_length=100, null=True, verbose_name='\u4e2a\u4eba\u4e3b\u9875'),
        ),
        migrations.AlterField(
            model_name='user',
            name='linkin',
            field=models.IntegerField(choices=[(0, '\u5df2\u6fc0\u6d3b'), (1, '\u672a\u6fc0\u6d3b')], default=1, verbose_name='\u662f\u5426\u5173\u8054linkin'),
        ),
        migrations.AlterField(
            model_name='user',
            name='stackoverflow',
            field=models.IntegerField(choices=[(0, '\u5df2\u6fc0\u6d3b'), (1, '\u672a\u6fc0\u6d3b')], default=1, verbose_name='\u662f\u5426\u6fc0\u6d3bstackoverflow'),
        ),
    ]
