# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-27 06:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vuser', '0013_auto_20161227_0609'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='companylocl',
            new_name='companylocal',
        ),
    ]
