# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-27 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuser', '0014_auto_20161227_0612'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='github',
            field=models.IntegerField(choices=[(0, '\u5df2\u6fc0\u6d3b'), (1, '\u672a\u6fc0\u6d3b')], default=1, verbose_name='\u662f\u5426\u6fc0\u6d3bgithub'),
        ),
    ]
