# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-27 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuser', '0015_user_github'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='headimg',
            field=models.ImageField(blank=True, null=True, upload_to='headimg/%Y/%m', verbose_name='\u4e2a\u4eba\u5934\u50cf'),
        ),
        migrations.AlterField(
            model_name='user',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resume/%Y/m', verbose_name='\u7b80\u5386'),
        ),
    ]
