# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-03 05:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vuser', '0017_auto_20161227_0830'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='\u52cb\u7ae0\u540d\u79f0')),
                ('imgurl', models.CharField(default='img/a.gif', max_length=50, null=True, verbose_name='\u52cb\u7ae0\u56fe\u7247\u4f4d\u7f6e')),
            ],
        ),
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeday', models.DateField(verbose_name='\u83b7\u5f97\u79ef\u5206\u65f6\u95f4,\u5929')),
                ('point', models.IntegerField(verbose_name='\u83b7\u5f97\u5206\u6570')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vuser.User')),
            ],
        ),
        migrations.AddField(
            model_name='usercourse',
            name='coursetime',
            field=models.IntegerField(default=0, verbose_name='\u89c2\u770b\u89c6\u9891\u7684\u4f4d\u7f6e'),
            preserve_default=False,
        ),
    ]
